import Head from 'next/head'
import Button from 'react-bootstrap/Button';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col'
import ComponentLibrariesList from '../components/ComponentLibrariesList';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h1>
            Nice.
          </h1>
          <Row>
            <Col>
              <Button variant="info">Example</Button>
            </Col>
            <Col>
              <h4>Available component libraries</h4>
              <ComponentLibrariesList />
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  )
}
