import Head from 'next/head'
import Image from 'next/image'
import Typography from '@mui/material/Typography'
import Container from '@mui/material/Container'
import JSArticles from '../components/JSArticles'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Assignment 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <NavBar />
          <Typography variant='h2' component='h2' color='primary' align='center'>Assignment 2 - React Components</Typography>
          <Typography color='secondary' align='center'>Here's a list of awesome resources that you can use</Typography>
          <JSArticles />
        </Container>
      </main>
    </div>
  )
}
