import {useState} from 'react'

import Head from 'next/head'

import AppBar from '@mui/material/AppBar';

import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Grid from '@mui/material/Grid';
import FormControl from '@mui/material/FormControl';
import FormLabel from '@mui/material/FormLabel';
import FormControlLabel from '@mui/material/FormControlLabel';

import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';

import TextField from '@mui/material/TextField';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

import AdaptationReviewCard from '../components/AdaptationReviewCard'
import AdaptationForm from '../components/AdaptationForm';

import { getReviews } from '../utils/api/reviews';

export default function Home() {
  const [reviews, setReviews] = useState([])

  const loadAllReviewsButton = () => {
    getReviews()
    .then((data)=> {
      setReviews(data)
    })
  }

  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container sx={{
            pt: 2,
            pb: 2,
          }}
          maxWidth="md"
        >
          <AdaptationForm
            setReviews={setReviews}
            reviews={reviews}
          />
          <Box
            sx={{
              pt: 2,
              pb: 2,
            }}
          >
            <Button
              variant="contained"
              onClick={loadAllReviewsButton}
            >
              Load All Current Reviews
            </Button>
          </Box>
          {reviews.map((adaptation, index)=> {
            return <AdaptationReviewCard
                key={index}
                rating={adaptation.rating}
                title={adaptation.title}
                comment={adaptation.comment}
              />
          })}
        </Container>
      </main>
    </div>
  )
}
